#!/usr/bin/env bash
set -euo pipefail

# Requires xxd installed: sudo apt install xxd
WASM="wasm/ic-icrc1-ledger.wasm"
OUT="src/factory/wasm_bytes_icrc1/lib.mo"

echo "Embedding ${WASM} into ${OUT}..."

# Create output directory if it doesn't exist
mkdir -p "$(dirname "$OUT")"

{
  echo "// AUTO-GENERATED by embed_icrc1_wasm.sh — do not edit."
  echo "module {"
  echo "  public let array : [Nat8] = ["
} > "$OUT"

# Embed wasm bytes
xxd -i "$WASM" \
  | sed '1d;$d;s/^/    /' \
  >> "$OUT"

{
  echo "  ];"
  echo "  public let wasm_len : Nat = Array.size(array);"
  echo "}"
} >> "$OUT"

echo "✅ lib.mo generated successfully."
