#!/usr/bin/env bash
set -euo pipefail

# Config
WASM="wasm/ic-icrc1-ledger.wasm"
OUT="src/factory/wasm_bytes_icrc1/lib.mo"
CHUNK_SIZE=8192  # 8 KB per chunk

echo "Embedding ${WASM} into ${OUT} with chunking..."

# Create output directory if it doesn't exist
mkdir -p "$(dirname "$OUT")"

# Clean temp directory
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

# Split wasm into hex bytes
xxd -p -c1 "$WASM" > "$TMPDIR/bytes.txt"

# Generate chunks
split -l $CHUNK_SIZE "$TMPDIR/bytes.txt" "$TMPDIR/chunk_"

# Start writing lib.mo
{
  echo "// AUTO-GENERATED by embed_icrc1_wasm.sh — do not edit."
  echo "module {"
  echo "  // Number of chunks"
  NUM_CHUNKS=$(ls $TMPDIR/chunk_* | wc -l)
  echo "  public let __num_chunks : Nat = ${NUM_CHUNKS};"
} > "$OUT"

# Write each chunk as a static array
i=0
for f in $TMPDIR/chunk_*; do
  echo -n "  public let chunk_${i} : [Nat8] = [" >> "$OUT"
  paste -sd "," "$f" | sed 's/\([0-9a-f][0-9a-f]\)/0x\1/g' >> "$OUT"
  echo "];" >> "$OUT"
  i=$((i+1))
done

# Close module
echo "}" >> "$OUT"

echo "✅ lib.mo generated successfully with ${NUM_CHUNKS} chunks."
