[package]
name = "token_factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.16"
ic-cdk-macros = "0.16"
serde = { version = "1.0", features = ["derive"] }
ic-ledger-types = "0.11"
icrc-ledger-types = "0.1"
